#!/bin/sh
# requires mblaze, jq, inotifywait
set -eu

MAILDIR=$HOME/Maildir
BOX=""

mboxicon() {
   case "$1" in
   *) printf %s "$1" |
      cut -c1-1 |
      tr '[:lower:]' '[:upper:]' ;;
   esac
}
mboxcolor() {
   case "$1" in
   "gmail") printf %s "pink" ;;
   "fastmail") printf %s "lightblue" ;;
   "zoho") printf %s "red" ;;
   *) printf %s "white" ;;
   esac
}

main() {
   CLASS="read"
   PERCENTAGE="0"
   TOOLTIP=""
   STATUS=""
   for BOX in *; do
      count=$(mlist -N "$BOX"/Inbox | wc -l)
      if [ "$count" -gt 0 ]; then
         icon=$(mboxicon "$BOX")
         color=$(mboxcolor "$BOX")
         STATUS="$STATUS<span foreground=\"$color\">$icon</span>$count"
         BOX_LABEL="$(echo "$BOX" | tr '[:lower:]' '[:upper:]')"
         TOOLTIP=$(
            printf %s "$TOOLTIP"
            echo "<span foreground=\"$color\"><u><b>$BOX_LABEL</b></u> ($count)</span>"
            mlist -N "$BOX"/Inbox | mscan -f '<small><tt>%d </tt><b>%f</b>\n<tt>\t%t</tt>%s</small>'
         )
      fi
   done

   if [ -n "$STATUS" ]; then
      CLASS="new"
      PERCENTAGE="100"
   fi

   jq -n --unbuffered --compact-output \
      --arg text "$STATUS" \
      --arg tooltip "$TOOLTIP" \
      --arg percentage "$PERCENTAGE" \
      --arg class "$CLASS" \
      '{"text": $text, "tooltip": $tooltip, "percentage": $percentage, "class": $class}'
}

loop() {
   cd "$MAILDIR"
   while true; do
      main
      find "$MAILDIR" -type d -exec inotifywait -qq -e modify,create,delete {} +
   done
}

case "${1-}" in
-h | --help)
   usage
   exit
   ;;
*)
   loop
   ;;
esac
