#!/bin/sh 
##############################################################################
# Reinstate all the dotfiles into their functional locations.
##############################################################################
mkdir ~/.emacs.d
ln -rs 'ackrc' ~/'.ackrc'
ln -rs 'autostart' ~/'.config/autostart'
ln -rs 'bash_profile' ~/'.bash_profile'
ln -rs 'bashrc' ~/'.bashrc'
ln -rs 'bin' ~/'bin'
ln -rs 'bspwm' ~/'.config/bspwm'
ln -rs 'dircolors' ~/'.dircolors'
ln -rs 'dunst' ~/'.config/dunst'
ln -rs 'fish' ~/'.config/fish'
ln -rs 'fonts' ~/'.fonts'
ln -rs 'gitconfig' ~/'.gitconfig'
ln -rs 'htoprc' ~/'.htoprc'
ln -rs 'i3/blocks' ~/'.config/i3blocks'
ln -rs 'i3' ~/'.i3'
ln -rs 'imapnotify' ~/'.config/imapnotify'
ln -rs 'irssi' ~/'.irssi'
ln -rs 'login' ~/'.login'
ln -rs 'mbsyncrc' ~/'.mbsyncrc'
ln -rs 'mpd' ~/'.config/mpd'
ln -rs 'mplayer' ~/'.mplayer'
ln -rs 'msmtprc' ~/'.msmtprc'
ln -rs 'ncmpcpp' ~/'.ncmpcpp'
ln -rs 'neomutt' ~/'.config/neomutt'
ln -rs 'npmrc' ~/'.npmrc'
ln -rs 'pandoc' ~/'.pandoc'
ln -rs 'pentadactyl' ~/'.pentadactyl'
ln -rs 'pentadactylrc' ~/'.pentadactylrc'
ln -rs 'screenrc' ~/'.screenrc'
ln -rs 'spacemacs/private' ~/'.emacs.d/private'
ln -rs 'spacemacs/spacemacs' ~/'.spacemacs'
ln -rs 'surface/sp3buttons.xkb' ~/'.config/sp3buttons.xkb'
ln -rs 'surface/sp3buttons.xkb' ~/'.config/sp3buttons.xkb'
ln -rs 'sxhkd' ~/'.config/sxhkd'
ln -rs 'systemd_user' ~/'.config/systemd'
ln -rs 'twmn' ~/'.config/twmn'
ln -rs 'uzbl/config' ~/'.config/uzbl'
ln -rs 'uzbl/local' ~/'.local/share/uzbl'
ln -rs 'vimrc' ~/'.vimrc'
ln -rs 'vim' ~/'.vim'
ln -rs 'weechat' /'.weechat'
ln -rs 'Xdefaults' ~/'.Xdefaults'
ln -rs 'xinitrc' ~/'.xinitrc'
ln -rs ~/'.xsessionrc' ~/'.login'
ln -rs 'zshenv' ~/'.zshenv'
ln -rs 'zshrc' ~/'.zshrc'
