#!/bin/bash

if [ ! -f ~/.stowrc ]; then
    echo "--target=$HOME" >> ~/.stowrc
fi

# apply the words in `uname -a` to dirnames in _systems/, for any match stow
# all the dirs.
UNAME=$(uname -a)
if [ -d _systems ]; then
    for name in $UNAME ; do
        for f in _systems/*; do
            if [ -d "$f" ] && (echo "$name" | grep -q "$f"); then
                cd "$f"
                ls | xargs -n1 stow
                cd -
            fi
        done
    done
fi
