colorscheme kaleidoscope-dark
source "%val{config}/plugins/plug.kak/rc/plug.kak"
plug "andreyorst/plug.kak" ensure

plug "andreyorst/fzf.kak" ensure config %{
    map global normal <c-p> ': fzf-mode<ret>'
} defer "fzf" %{
    set-option global fzf_file_command 'rg'
    set-option global fzf_highlight_command 'bat'
}

plug "topisani/auto-pairs.kak" ensure config %{
    hook global WinCreate .* %{
        auto-pairs-enable
    }

    map global user s -docstring 'Surround' ':auto-pairs-surround<ret>'
}

plug "TeddyDD/kakoune-edit-or-dir" ensure config %{
    unalias global e edit
    alias global e edit-or-dir
}

plug "andreyorst/smarttab.kak" defer smarttab %{
     set-option global softtabstop 4
} config %{
     # these languages will use `expandtab' behavior
     hook global WinSetOption filetype=(rust|markdown|kak|lisp|scheme|sh|perl) expandtab
     # these languages will use `noexpandtab' behavior
     hook global WinSetOption filetype=(makefile|gas) noexpandtab
     # these languages will use `smarttab' behavior
     hook global WinSetOption filetype=(c|cpp) smarttab
}
