#!/bin/sh

escapeDbusPath() {
    # $SERVICE into systemd+dbus path, only [a-zA-Z0-9_] allowed.
    # TODO: be smarter
    echo "$1" | tr '-' '_2d' | tr '.' '_2e'
}

monitor() {
    dbus-monitor --system --profile "type='signal',path='/org/freedesktop/systemd1/unit/$(escape $1)',member='PropertiesChanged'"
}

# TODO: pipe monitor() into while read loop
# monitor |\
#     while read line; do
#         # TODO: get timestamp, echo json, debounce based on timestamp (1s is good enough)
#         continue
#     done

SERVICE="$1"
STATUS=$(systemctl is-active $SERVICE)

TOOLTIP="$SERVICE is inactive"
CLASS=inactive
TEXT=inactive
PERCENTAGE=0

if [ "$2" == "toggle" ]; then
    echo $2 $1 : $STATUS
    if [ "$STATUS" == active ]; then
        kdesu -c "systemctl stop $SERVICE"
    else
        kdesu -c "systemctl start $SERVICE"
    fi
    exit
fi

if [ "$STATUS" == active ]; then
    TOOLTIP="$SERVICE is active"
    CLASS=active
    TEXT=active
    PERCENTAGE=100
fi

echo $"{ \"text\": \"$TEXT\", \"percentage\": $PERCENTAGE, \"tooltip\": \"$TOOLTIP\", \"class\": \"$CLASS\" }"
