vim.keymap.set('x', 'gc', '<Plug>VSCodeCommentary', {})
vim.keymap.set('n', 'gc', '<Plug>VSCodeCommentary', {})
vim.keymap.set('o', 'gc', '<Plug>VSCodeCommentary', {})
vim.keymap.set('n', 'gcc', '<Plug>VSCodeCommentaryLine', {})
vim.keymap.set('n', '<Space>/', function() vscode.call('workbench.action.quickTextSearch') end, {})
vim.keymap.set('n', '<Space>bd', function() vscode.call('workbench.action.closeActiveEditor') end, {})
