on:
  pull_request:
  push:
    branches: [main]

jobs:
  check:
    name: Check nix flake
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check Nix flake inputs
        uses: DeterminateSystems/flake-checker-action@v5 # This action
        with:
          ignore-missing-flake-lock: false
          fail-mode: true
